HTML Lesson 4 Shumyakova (index.txt)
LizaShu/html-markup-home-Shumyakova pull request #1
Opened 2022-07-11 15:03 UTC by LizaShu

Александр, извините, что кучу коммитов сделала( Не совсем понимаю, что лучше коммитить, какую-то часть текста? или отдельно по тегам?

2022-07-14 23:17 UTC, instinct-it-academy requested changes
Добрый вечер, задание на небольшую доработку. Обратите внимание на комментарии и на форматирование кода - отступы и структура кода. Форматирование не входило в условие задания, но т.к. есть моменты которые необходимо подправить, было бы хорошо уделить и этому немного времени.

2022-07-14 23:17 UTC, instinct-it-academy commented on home-4-html-4-intro/index.txt
> +<!DOCTYPE html>
![image](https://user-images.githubusercontent.com/29653615/179116117-aefd2104-cd0b-440e-9cec-8dbd8abe3d15.png)
в данном задании не критично, учитывая что заданием было изучение тегов можно и каждый новый зафиксировать. В целом в качестве коммита выступает некоторый законченный кусочек работы, функционала. Учитывая то что задание не сложное и не большое вполне мог быть и один коммит.

2022-07-14 23:17 UTC, instinct-it-academy commented on home-4-html-4-intro/index.txt
> +    </div>
![image](https://user-images.githubusercontent.com/29653615/179116304-9117dbc5-c1c3-4f7b-9f3d-cf61570b3e62.png)
не корректно, т.к. сначала тег должен открываться , потом закрываться. Необходимо поменять местами. При это h - уже блочный тег, его можно не оборачивать в div

2022-07-14 23:17 UTC, instinct-it-academy commented on home-4-html-4-intro/index.txt
> +              <td width="100"><strong>Название</strong></td>
![image](https://user-images.githubusercontent.com/29653615/179116497-d416ffc7-2f76-4328-9ee6-a69a84e8f862.png)
Если выделили строку под заголовки, было бы хорошо везде использовать th

2022-07-15 11:45 UTC, LizaShu commented on home-4-html-4-intro/index.txt
> +    </div>
Исправила теги dev

2022-07-15 11:46 UTC, LizaShu commented on home-4-html-4-intro/index.txt
> +              <td width="100"><strong>Название</strong></td>
Заменила теги в строке на th

2022-07-29 15:29 UTC, closed without merging